version: 2.1

orbs:
  maven:  circleci/maven@0.0.12
jobs: 
  test: 
    docker:
      - image: buildpack-deps:trusty
    steps: 
               
      - run:
          name: TestLogService
          command: |
            git clone https://github.com/davinchicoronado/TallerArepAppSegura.git 
      
workflows:
  maven_test:
    jobs:
      - test
