version: '2'

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24



services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web
        networks:
            frontend:
                ipv4_address: 172.20.0.5
        ports:
            - "8087:6000"
        
